<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5cd2e48b333a3',
	'title' => 'Block: FAS',
	'fields' => array(
		array(
			'key' => 'field_5cd2e496e6707',
			'label' => 'Font Awesome Icon',
			'name' => 'fas_icon',
			'type' => 'text',
			'instructions' => 'Insert Font Awesome shortcode of an icon you\'d like. You may also include things like size. Example: "fa-handshake fa-2x"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/fas',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ccae431ac4e8',
	'title' => 'Block: Hero',
	'fields' => array(
		array(
			'key' => 'field_5ccae47c56aa3',
			'label' => 'Hero Background Image URL',
			'name' => 'hero_background_image_url',
			'type' => 'url',
			'instructions' => 'URL for background image in hero.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ccae4c50dfe2',
			'label' => 'Hero Title',
			'name' => 'hero_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ccae4e56502c',
			'label' => 'Hero Text',
			'name' => 'hero_text',
			'type' => 'textarea',
			'instructions' => 'Text area for the hero.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ccb12221dd7a',
			'label' => 'Hero Button',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ccb0bc088f55',
			'label' => 'Hero Button URL',
			'name' => 'hero_button_url',
			'type' => 'url',
			'instructions' => 'Where do you want to link this button to?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ccb0d2ffb93f',
			'label' => 'Hero Button Text',
			'name' => 'hero_button_text',
			'type' => 'text',
			'instructions' => 'Text for the button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ccb151280fc9',
			'label' => 'Button coloring',
			'name' => '',
			'type' => 'accordion',
			'instructions' => 'Coloring for the button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd4190b7551d',
			'label' => 'Hero Button Background Color',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ccb12b3211c6',
			'label' => 'Hero Button Background Color',
			'name' => 'hero_button_background_color',
			'type' => 'color_picker',
			'instructions' => 'Background color for the button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array(
			'key' => 'field_5cd4191e7551e',
			'label' => 'Hero Button Border Color',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ccb1371d0089',
			'label' => 'Hero Button Border Color',
			'name' => 'hero_button_border_color',
			'type' => 'color_picker',
			'instructions' => 'Border color for the button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000000',
		),
		array(
			'key' => 'field_5cd419977551f',
			'label' => 'Hero Button Text Color',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ccb149d485f0',
			'label' => 'Hero Button Text Color',
			'name' => 'hero_button_text_color',
			'type' => 'color_picker',
			'instructions' => 'Color for the link text inside the button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array(
			'key' => 'field_5cd419c775520',
			'label' => 'Hero Button Text Hover Color',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ccb152d303c9',
			'label' => 'Heru Button Text Hover Color',
			'name' => 'hero_button_text_hover_color',
			'type' => 'color_picker',
			'instructions' => 'Coloring for link text when you hover over the button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5cd419d675521',
			'label' => 'Hero Button Background Hover Color',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ccb17d5c959a',
			'label' => 'Hero Button Background Hover Color',
			'name' => 'hero_button_backround_hover_color',
			'type' => 'color_picker',
			'instructions' => 'Background coloring for when you hover over the button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/hero',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
		1 => 'discussion',
		2 => 'comments',
		3 => 'featured_image',
		4 => 'categories',
		5 => 'tags',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cbf098fc6f98',
	'title' => 'Contact form',
	'fields' => array(
		array(
			'key' => 'field_5cc05af861599',
			'label' => 'Contact form ID',
			'name' => 'contact_form_id',
			'type' => 'number',
			'instructions' => 'Insert the ID of your contact form to make sure it exists.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5cd11485d2675',
			'label' => 'Contact form shortcode',
			'name' => 'contact_form_shortcode',
			'type' => 'wysiwyg',
			'instructions' => 'Insert shortcode from contact form here. For advanced users, you can insert pure HTML here if you\'d like.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sosa_contact',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cc84fd60dc4d',
	'title' => 'Dog',
	'fields' => array(
		array(
			'key' => 'field_5cd3a6e06d573',
			'label' => 'Image',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cc84fddcda04',
			'label' => 'Image',
			'name' => 'dog_image',
			'type' => 'image',
			'instructions' => 'Image thumbnail for dog.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5cd3a6f8d3b77',
			'label' => 'Dates',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd3a9cfcb073',
			'label' => 'Before you add the dog:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Please do note type in the fields, choose from the date picker or some things will not work properly, like the age value of the dog. You can still type in the fields if you\'d like, but the format has to be identical to what the date picker outputs.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5cd10fce6e864',
			'label' => 'Birthdate',
			'name' => 'dog_birth_date',
			'type' => 'date_picker',
			'instructions' => 'Birthdate of the dog.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5cd00d199e6ae',
			'label' => 'Adoption date',
			'name' => 'dog_adoption_date',
			'type' => 'date_picker',
			'instructions' => 'Date of which the dog was adopted. Leave empty if not adopted.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5cd3a6f4d3b74',
			'label' => 'Traits',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd3a6643c339',
			'label' => 'Sex',
			'name' => 'dog_sex',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Male' => 'Male',
				'Female' => 'Female',
			),
			'allow_null' => 0,
			'other_choice' => 1,
			'save_other_choice' => 1,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cd00c469e6ac',
			'label' => 'Withers',
			'name' => 'dog_withers',
			'type' => 'number',
			'instructions' => 'Withers of the dog, in centimeters.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5cd00cb59e6ad',
			'label' => 'Weight',
			'name' => 'dog_weight',
			'type' => 'number',
			'instructions' => 'Weight of the dog, in kilograms.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sosa_dog',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'featured_image',
		1 => 'tags',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd2f3e13a524',
	'title' => 'Success Story',
	'fields' => array(
		array(
			'key' => 'field_5cd3afaec5b25',
			'label' => 'Background image',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd3b0440c900',
			'label' => 'Before you add an image:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Please only pick one method. Using both may result in one overriding the other.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5cd3af7fc5b24',
			'label' => 'SS Background image',
			'name' => 'ss_background_image',
			'type' => 'image',
			'instructions' => 'Image file for the background of the success story.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5cd3afcac5b26',
			'label' => 'SS Background image URL',
			'name' => 'ss_background_image_url',
			'type' => 'url',
			'instructions' => 'Image URL for the background of the success story.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sosa_ss',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cc99b234098a',
	'title' => 'Theme Options',
	'fields' => array(
		array(
			'key' => 'field_5cc99b49d6e0b',
			'label' => 'SOSA Options',
			'name' => '',
			'type' => 'accordion',
			'instructions' => 'Note that most of these are temporarily out of order. Contact the administrator if you want these funtioncalities back.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cc99b64d6e0c',
			'label' => 'How many dogs to display on frontpage',
			'name' => 'amount_of_dogs_frontpage',
			'type' => 'number',
			'instructions' => 'How many dogs you wish to display on the frontpage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Dogs',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5ccc4ffd34162',
			'label' => 'How many dogs to display per page in archive',
			'name' => 'amount_of_dogs_archive',
			'type' => 'number',
			'instructions' => 'How many dogs you wish to display per page in the archive.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Dogs',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5ccafa71b5a4a',
			'label' => 'How many USPs to display on frontpage',
			'name' => 'amount_of_usps_frontpage',
			'type' => 'number',
			'instructions' => 'How many USPs you wish to display on the frontpage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'USPs',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cc8675c9f488',
	'title' => 'USP Frontpage',
	'fields' => array(
		array(
			'key' => 'field_5cc8676410d23',
			'label' => 'USP Frontpage Icon',
			'name' => 'usp_frontpage_icon',
			'type' => 'text',
			'instructions' => 'Shortcode for icon usage, preferably Font Awesome',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cc86bb12a06f',
			'label' => 'USP Frontpage Icon Amount',
			'name' => 'usp_frontpage_icon_amount',
			'type' => 'number',
			'instructions' => 'How many times do you want to display the icon?

! WIP !',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sosa_usp',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;